python rej2eve.py ya1
python rej2eve.py ya2
python rej2eve.py ya3
python rej2eve.py ya4
python rej2eve.py ya5
python rej2eve.py ya6
python rej2eve.py ya7
python rej2eve.py ya8
python rej2eve.py ya9
python rej2eve.py ya12
python rej2eve.py ya13
python rej2eve.py ya15
python rej2eve.py ya16
python rej2eve.py ya17
python rej2eve.py ya18
python rej2eve.py ya19
python rej2eve.py ya20
python rej2eve.py ya21
python rej2eve.py ya22
python rej2eve.py ya23
python rej2eve.py ya24
python rej2eve.py ya25
python rej2eve.py ya26
python rej2eve.py ya27
python rej2eve.py ya29
python rej2eve.py ya30
python rej2eve.py ya31
python rej2eve.py ya32
python rej2eve.py ya33
python cmpEve.py ya1
python cmpEve.py ya2
python cmpEve.py ya3
python cmpEve.py ya4
python cmpEve.py ya5
python cmpEve.py ya6
python cmpEve.py ya7
python cmpEve.py ya8
python cmpEve.py ya9
python cmpEve.py ya10
python cmpEve.py ya11
python cmpEve.py ya12
python cmpEve.py ya13
python cmpEve.py ya14
python cmpEve.py ya15
python cmpEve.py ya16
python cmpEve.py ya17
python cmpEve.py ya18
python cmpEve.py ya19
python cmpEve.py ya20
python cmpEve.py ya21
python cmpEve.py ya22
python cmpEve.py ya23
python cmpEve.py ya24
python cmpEve.py ya25
python cmpEve.py ya26
python cmpEve.py ya27
python cmpEve.py ya28
python cmpEve.py ya29
python cmpEve.py ya30
python cmpEve.py ya31
python cmpEve.py ya32
python cmpEve.py ya33