#!/bin/csh

setenv SUBJECT $1 

###ORGANIZE DICOMS###

cd $SUBJECTS_DIR/$1/bem/flash_org
echo $SUBJECTS_DIR
mne_organize_dicom ../flash_dcm
ln -s 0*5d* flash05

###Set up MRI images for MRILab and setup source space##

mne_setup_mri
mne_setup_source_space

###Create bem surfaces###

mne_flash_bem --noflash30

###Create symbolic links to the bem surfaces###

cd /cluster/kuperberg/SemPrMM/MRI/structurals/subjects/$1/bem

ln -s ./flash/outer_skin.surf outer_skin.surf
ln -s ./flash/outer_skull.surf outer_skull.surf
ln -s ./flash/inner_skull.surf inner_skull.surf


mne_surf2bem \
--surf $SUBJECTS_DIR/$1/bem/outer_skin.surf --id 4 \
--surf $SUBJECTS_DIR/$1/bem/outer_skull.surf --id 3 \
--surf $SUBJECTS_DIR/$1/bem/inner_skull.surf --id 1 \
--fif $SUBJECTS_DIR/$1/bem/$1-bem.fif


#mne_watershed_bem  
##use this if the flash surfaces don't work

mne_setup_forward_model --surf --ico 4
