#!/bin/csh

cd /cluster/kuperberg/SemPrMM/MEG/data/$1

mkdir logs
mkdir eve
mkdir ave
mkdir cov
mkdir ave_projon
mkdir ave_projoff
mkdir ave_projon/logs
mkdir ave_projoff/logs



################################################################
##Save read-only copy of raw-files and make other ones writeable

if ( ! -d "raw_backup" ) then
	mkdir raw_backup
	cp *_raw.fif raw_backup
endif

chmod u=rwx *_raw.fif

#############################################################
##Extracting events read from .fif files into .eve text files

echo
echo "Extracting events"


if ( -e $1_Blink_raw.fif ) then
	#Blink
	echo mne_process_raw --raw $1_Blink_raw.fif --eventsout eve/$1_Blink.eve
	mne_process_raw --raw $1_Blink_raw.fif --eventsout eve/$1_Blink.eve
endif


#ATLLoc
echo mne_process_raw --raw $1_ATLLoc_raw.fif --eventsout eve/$1_ATLLoc.eve
mne_process_raw --raw $1_ATLLoc_raw.fif --eventsout eve/$1_ATLLoc.eve

#MaskedMM
foreach j ( 1 2)
	echo mne_process_raw --raw $1_MaskedMMRun${j}_raw.fif --eventsout eve/$1_MaskedMMRun$j.eve
	mne_process_raw --raw $1_MaskedMMRun${j}_raw.fif --eventsout eve/$1_MaskedMMRun$j.eve
end

#BALEEN
foreach i ( 1 2 3 4 5 6 7 8)
	echo mne_process_raw --raw $1_BaleenRun${i}_raw.fif --eventsout eve/$1_BaleenRun$i.eve
	mne_process_raw --raw $1_BaleenRun${i}_raw.fif --eventsout eve/$1_BaleenRun$i.eve
end

if ( -e $1_AXCPTRun1_raw.fif ) then
	echo mne_process_raw --raw $1_AXCPTRun1_raw.fif --eventsout eve/$1_AXCPTRun1.eve
	mne_process_raw --raw $1_AXCPTRun1_raw.fif --eventsout eve/$1_AXCPTRun1.eve
endif

if ( -e $1_AXCPTRun2_raw.fif ) then
	echo mne_process_raw --raw $1_AXCPTRun2_raw.fif --eventsout eve/$1_AXCPTRun2.eve
	mne_process_raw --raw $1_AXCPTRun2_raw.fif --eventsout eve/$1_AXCPTRun2.eve
endif


##############################################
echo
echo "Fixing triggers"

python /cluster/kuperberg/SemPrMM/MEG/scripts/fixTriggers.py $1


##############################################
echo
echo "Renaming EEG channels"

if ( $1 == 'ya1' | $1 == 'ya3' |$1 == 'ya4' |$1 == 'ya7' ) then
	foreach f ( *_raw.fif )
		mne_rename_channels --fif $f --alias ../../scripts/alias1.txt
		mne_check_eeg_locations --file $f --fix
	end
endif


foreach f ( *_raw.fif )
	mne_rename_channels --fif $f --alias ../../scripts/alias2.txt
end


##############################################
###Marking bad channels

echo
echo "Marking bad channels"

if ( -e $1_bad_chan.txt ) then
	foreach f ( *_raw.fif )
		mne_mark_bad_channels --bad $1_bad_chan.txt $f
	end
endif

echo



