#!/bin/csh

#usage: preProc subjID preBlinkTime postBlinkTime
#example: preproc ya16 -0.1 0.4

cd /cluster/kuperberg/SemPrMM/MEG/data/$1

mkdir eve
mkdir ave
mkdir cov
mkdir ave_projon
mkdir ave_projoff
mkdir ave_projon/logs
mkdir ave_projoff/logs


################################################################
##Save read-only copy of raw-files and make other ones writeable

if ( ! -d "raw_backup" ) then
	mkdir raw_backup
	cp *_raw.fif raw_backup
endif

chmod u=rwx *_raw.fif

#############################################################
##Extracting events read from .fif files into .eve text files

echo
echo "Extracting events"


if ( -e $1_Blink_raw.fif ) then
	#Blink
	echo mne_process_raw --raw $1_Blink_raw.fif --eventsout eve/$1_Blink.eve
	mne_process_raw --raw $1_Blink_raw.fif --eventsout eve/$1_Blink.eve
endif


#ATLLoc
echo mne_process_raw --raw $1_ATLLoc_raw.fif --eventsout eve/$1_ATLLoc.eve
mne_process_raw --raw $1_ATLLoc_raw.fif --eventsout eve/$1_ATLLoc.eve

#MaskedMM
foreach j ( 1 2)
	echo mne_process_raw --raw $1_MaskedMMRun${j}_raw.fif --eventsout eve/$1_MaskedMMRun$j.eve
	mne_process_raw --raw $1_MaskedMMRun${j}_raw.fif --eventsout eve/$1_MaskedMMRun$j.eve
end

#BALEEN
foreach i ( 1 2 3 4 5 6 7 8)
	echo mne_process_raw --raw $1_BaleenRun${i}_raw.fif --eventsout eve/$1_BaleenRun$i.eve
	mne_process_raw --raw $1_BaleenRun${i}_raw.fif --eventsout eve/$1_BaleenRun$i.eve
end


if ( -e $1_AXCPTRun1_raw.fif ) then
	echo mne_process_raw --raw $1_AXCPTRun1_raw.fif --eventsout eve/$1_AXCPTRun1.eve
	mne_process_raw --raw $1_AXCPTRun1_raw.fif --eventsout eve/$1_AXCPTRun1.eve
endif

if ( -e $1_AXCPTRun2_raw.fif ) then
	echo mne_process_raw --raw $1_AXCPTRun2_raw.fif --eventsout eve/$1_AXCPTRun2.eve
	mne_process_raw --raw $1_AXCPTRun2_raw.fif --eventsout eve/$1_AXCPTRun2.eve
endif


##############################################
echo
echo "Fixing triggers"

python /cluster/kuperberg/SemPrMM/MEG/scripts/fixTriggers.py $1


##############################################
echo
echo "Renaming EEG channels"

if ( $1 == 'ya1' | $1 == 'ya3' |$1 == 'ya4' |$1 == 'ya7' ) then
	foreach f ( *_raw.fif )
		mne_rename_channels --fif $f --alias ../../scripts/alias1.txt
		mne_check_eeg_locations --file $f --fix
	end
endif


foreach f ( *_raw.fif )
	mne_rename_channels --fif $f --alias ../../scripts/alias2.txt
end


##############################################
###Marking bad channels

echo
echo "Marking bad channels"

if ( -e $1_bad_chan.txt ) then
	foreach f ( *_raw.fif )
		mne_mark_bad_channels --bad $1_bad_chan.txt $f
	end
endif

echo




###########################
echo
echo "Making Ave Parameter Files"
python /cluster/kuperberg/SemPrMM/MEG/scripts/makeAveFiles.py $1 $2 $3

echo
echo "Making blink .eve Files"
python /cluster/kuperberg/SemPrMM/MEG/scripts/blinkEveFiles.py $1 $2 $3

echo
echo "Making Cov Parameter Files"
python /cluster/kuperberg/SemPrMM/MEG/scripts/makeCovFiles.py $1 $2 $3




##########################
###projon averages

cd /cluster/kuperberg/SemPrMM/MEG/data/$1/ave_projon

mne_process_raw \
--raw ../$1_ATLLoc_raw.fif \
--ave ../ave/$1_ATLLoc.ave \
#--cov ../cov/$1_ATLLoc.cov  \
--projon --lowpass 20 --highpass .5

mne_process_raw \
--raw ../$1_MaskedMMRun1_raw.fif \
--raw ../$1_MaskedMMRun2_raw.fif \
--ave ../ave/$1_MaskedMMRun1.ave \
--ave ../ave/$1_MaskedMMRun2.ave \
--gave $1_MaskedMM_All-ave.fif \
--cov ../cov/$1_MaskedMMRun1.cov \
--cov ../cov/$1_MaskedMMRun2.cov \
--gcov $1_MaskedMM_All-cov.fif \
--projon --lowpass 20

mne_process_raw \
--raw ../$1_BaleenRun1_raw.fif \
--raw ../$1_BaleenRun2_raw.fif \
--raw ../$1_BaleenRun3_raw.fif \
--raw ../$1_BaleenRun4_raw.fif \
--ave ../ave/$1_BaleenRun1.ave \
--ave ../ave/$1_BaleenRun2.ave \
--ave ../ave/$1_BaleenRun3.ave \
--ave ../ave/$1_BaleenRun4.ave \
--gave $1_BaleenLP_All-ave.fif \
#--cov ../cov/$1_BaleenRun1.cov \
#--cov ../cov/$1_BaleenRun2.cov \
#--cov ../cov/$1_BaleenRun3.cov \
#--cov ../cov/$1_BaleenRun4.cov \
#--gcov $1_BaleenLP_All-cov.fif \
--projon --lowpass 20

mne_process_raw \
--raw ../$1_BaleenRun5_raw.fif \
--raw ../$1_BaleenRun6_raw.fif \
--raw ../$1_BaleenRun7_raw.fif \
--raw ../$1_BaleenRun8_raw.fif \
--ave ../ave/$1_BaleenRun5.ave \
--ave ../ave/$1_BaleenRun6.ave \
--ave ../ave/$1_BaleenRun7.ave \
--ave ../ave/$1_BaleenRun8.ave \
--gave $1_BaleenHP_All-ave.fif \
#--cov ../cov/$1_BaleenRun5.cov \
#--cov ../cov/$1_BaleenRun6.cov \
#--cov ../cov/$1_BaleenRun7.cov \
#--cov ../cov/$1_BaleenRun8.cov \
#--gcov $1_BaleenHP_All-cov.fif \
--projon --lowpass 20

mne_process_raw \
--raw ../$1_BaleenRun1_raw.fif \
--raw ../$1_BaleenRun2_raw.fif \
--raw ../$1_BaleenRun3_raw.fif \
--raw ../$1_BaleenRun4_raw.fif \
--raw ../$1_BaleenRun5_raw.fif \
--raw ../$1_BaleenRun6_raw.fif \
--raw ../$1_BaleenRun7_raw.fif \
--raw ../$1_BaleenRun8_raw.fif \
--cov ../cov/$1_BaleenRun1.cov \
--cov ../cov/$1_BaleenRun2.cov \
--cov ../cov/$1_BaleenRun3.cov \
--cov ../cov/$1_BaleenRun4.cov \
--cov ../cov/$1_BaleenRun5.cov \
--cov ../cov/$1_BaleenRun6.cov \
--cov ../cov/$1_BaleenRun7.cov \
--cov ../cov/$1_BaleenRun8.cov \
--gcov $1_Baleen_All-cov.fif \

--projon --lowpass 20




if ( -e ../$1_AXCPTRun1_raw.fif ) then
	if ( -e ../$1_AXCPTRun2_raw.fif ) then
		mne_process_raw \
		--raw ../$1_AXCPTRun1_raw.fif \
		--raw ../$1_AXCPTRun2_raw.fif \
		--ave ../ave/$1_AXCPTRun1.ave \
		--ave ../ave/$1_AXCPTRun2.ave \
		--cov ../cov/$1_AXCPTRun1.cov \
		--cov ../cov/$1_AXCPTRun2.cov \
		--gave $1_AXCPT_All-ave.fif \
		--gcov $1_AXCPT_All-cov.fif \
		--projoff --lowpass 20
	else
		mne_process_raw \
		--raw ../$1_AXCPTRun1_raw.fif \
		--cov ../cov/$1_AXCPTRun1.cov \
		--ave ../ave/$1_AXCPTRun1.ave \
		--gave $1_AXCPT_All-ave.fif \
		--gcov $1_AXCPT_All-cov.fif \
		--projoff --lowpass 20		
	endif
endif




####################################

echo "Counting events"

python /cluster/kuperberg/SemPrMM/MEG/scripts/countEvents.py $1 0 ATLLoc 1 projon
python /cluster/kuperberg/SemPrMM/MEG/scripts/countEvents.py $1 0 MaskedMM 2 projon
python /cluster/kuperberg/SemPrMM/MEG/scripts/countEvents.py $1 0 Baleen 8 projon

if ( -e $1_AXCPTRun1_raw.fif ) then
	if ( -e $1_AXCPTRun2_raw.fif ) then
		python /cluster/kuperberg/SemPrMM/MEG/scripts/countEvents.py $1 0 AX-CPT 2 projon
	else
		python /cluster/kuperberg/SemPrMM/MEG/scripts/countEvents.py $1 0 AX-CPT 1 projon
	endif
endif

##############################
###projoff averages

cd /cluster/kuperberg/SemPrMM/MEG/data/$1/ave_projoff

mne_process_raw \
--raw ../$1_ATLLoc_raw.fif \
--ave ../ave/$1_ATLLoc.ave \
--projoff --lowpass 20 --highpass .5

mne_process_raw \
--raw ../$1_MaskedMMRun1_raw.fif \
--raw ../$1_MaskedMMRun2_raw.fif \
--ave ../ave/$1_MaskedMMRun1.ave \
--ave ../ave/$1_MaskedMMRun2.ave \
--gave $1_MaskedMM_All-ave.fif \
--projoff --lowpass 20

mne_process_raw \
--raw ../$1_BaleenRun1_raw.fif \
--raw ../$1_BaleenRun2_raw.fif \
--raw ../$1_BaleenRun3_raw.fif \
--raw ../$1_BaleenRun4_raw.fif \
--ave ../ave/$1_BaleenRun1.ave \
--ave ../ave/$1_BaleenRun2.ave \
--ave ../ave/$1_BaleenRun3.ave \
--ave ../ave/$1_BaleenRun4.ave \
--gave $1_BaleenLP_All-ave.fif \
--projoff --lowpass 20

mne_process_raw \
--raw ../$1_BaleenRun5_raw.fif \
--raw ../$1_BaleenRun6_raw.fif \
--raw ../$1_BaleenRun7_raw.fif \
--raw ../$1_BaleenRun8_raw.fif \
--ave ../ave/$1_BaleenRun5.ave \
--ave ../ave/$1_BaleenRun6.ave \
--ave ../ave/$1_BaleenRun7.ave \
--ave ../ave/$1_BaleenRun8.ave \
--gave $1_BaleenHP_All-ave.fif \
--projoff --lowpass 20


if ( -e ../$1_AXCPTRun1_raw.fif ) then
	if ( -e ../$1_AXCPTRun2_raw.fif ) then
		mne_process_raw \
		--raw ../$1_AXCPTRun1_raw.fif \
		--raw ../$1_AXCPTRun2_raw.fif \
		--ave ../ave/$1_AXCPTRun1.ave \
		--ave ../ave/$1_AXCPTRun2.ave \
		--gave $1_AXCPT_All-ave.fif \
		--projoff --lowpass 20
	else
		mne_process_raw \
		--raw ../$1_AXCPTRun1_raw.fif \
		--ave ../ave/$1_AXCPTRun1.ave \
		--projoff --lowpass 20		
	endif
endif



####################################

#echo "Counting events"

python /cluster/kuperberg/SemPrMM/MEG/scripts/countEvents.py $1 0 ATLLoc 1 projoff
python /cluster/kuperberg/SemPrMM/MEG/scripts/countEvents.py $1 0 MaskedMM 2 projoff
python /cluster/kuperberg/SemPrMM/MEG/scripts/countEvents.py $1 0 Baleen 8 projoff

if ( -e $1_AXCPTRun1_raw.fif ) then
	if ( -e $1_AXCPTRun2_raw.fif ) then
		python /cluster/kuperberg/SemPrMM/MEG/scripts/countEvents.py $1 0 AX-CPT 2 projoff
	else
		python /cluster/kuperberg/SemPrMM/MEG/scripts/countEvents.py $1 0 AX-CPT 1 projoff
	endif
endif


